version: "3"
services:
  postgres:
    image: "postgres:15.2"
    ports:
      - "5432:5432"
    networks:
      - medtool-net
    restart: always
    volumes:
      - ./scripts:/scripts:ro
      - ./backups:/backups:rw
      - medtool-pg-data:/var/lib/postgresql/data/:rw
    environment:
      - "TZ=Europe/Moscow"
      - "PGTZ=Europe/Moscow"
      - "POSTGRES_PASSWORD=postgres"
      - "PGDATA=/var/lib/postgresql/data/"
    logging:
      options:
        max-size: "1024k"
        max-file: "5"

  back:
    image: "osipovskijdima/medtool-back:20230526.2"
    ports:
      - "8080:8080"
    networks:
      - medtool-net
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file: environment.env
    depends_on:
      - postgres
    logging:
      options:
        max-size: "1024k"
        max-file: "5"

  front:
    image: "osipovskijdima/medtool-front:20230526.2"
    ports:
      - "80:80"
    networks:
      - medtool-net
    restart: always
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - back
    logging:
      options:
        max-size: "1024k"
        max-file: "5"

volumes:
  medtool-pg-data:

networks:
  medtool-net:
    driver: bridge
