version: "3"
services:
  postgres:
    image: "postgres:15.2"
    ports:
      - "5432:5432"
    networks:
      - medtool-net
    restart: always
    volumes:
      - ./scripts:/scripts:ro
      - ./backups:/backups:rw
      - medtool-pg-data:/var/lib/postgresql/data/:rw
    environment:
      - "TZ=Europe/Moscow"
      - "PGTZ=Europe/Moscow"
      - "POSTGRES_PASSWORD=postgres"
      - "PGDATA=/var/lib/postgresql/data/"
    logging:
      options:
        max-size: "1024k"
        max-file: "5"

volumes:
  medtool-pg-data:

networks:
  medtool-net:
    driver: bridge
