#!/bin/sh

WDIR=./
BDIR=./backups

# shellcheck disable=SC2164
cd $WDIR

# in case if docker-compose does not work we can use docker exec (make sure container id is correct in this case)
# docker exec -t 604194225fb2 pg_dump -U postgres astral_security_crm > $BDIR/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
# shellcheck disable=SC2046
# shellcheck disable=SC2006
docker-compose exec -T postgres pg_dump -c -U postgres medtool > $BDIR/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql

# Now remove old backups
find $BDIR -type f -name '*.sql' -mtime +3 -delete >/dev/null 2>&1
